name = "weather-subscribers"
main = "index.js"
compatibility_date = "2024-01-01"

[vars]
ADMIN_PASSWORD = "weather@2024"

[[kv_namespaces]]
binding = "SUBSCRIBERS_KV"
id = "0d3820c31a6141608a04aeb69b586c0b"
